[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.124.2",
    "httpx>=0.28.1",
    "pytest>=9.0.2",
    "sqlalchemy>=2.0.36",
    "uvicorn>=0.38.0",
    "psycopg[binary]>=3.2.3",
]
